### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Jackiechao020** [frankNiessen/PTMC#2]
Hi Frank:
Thank you for this code. This helps a lot since the original PTMC paper is very difficult to understand.
Here is an error message when I first run the code. I have solved the error, but maybe I can share my experience to those who may use this code in the future.
The error message "Unable to resolve the name 'nntype.data"appears after I enter the twinning plane. 
![PTMC error message](https://github.com/frankNiessen/PTMC/assets/114793332/a3871e00-9e07-4b34-bd0b-30035331b0fd)
I think "nntype.data" is not a built-in Matlab functions, so the error message appear. Here I open "normc.m" file in the src folder, and change the following code:
x = nntype.data('format', x, 'Data');
into
if wasMatrix
    x = {x};
end
After this change, the Matlab code runs properly.

**Comment by Jackiechao020** [comment]
> Hi frank:
> 
> I have run the PTMC code in Matlab. However, an error message 'Unable to resolve the name 'nntype.data'.' appeared. Can I ask how to fix this problem? Thanks! ![PTMC error message](https://private-user-images.githubusercontent.com/114793332/335151732-41c8dd24-c339-4d89-ac37-e933af5e2892.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjY1MzgsIm5iZiI6MTcxNzA2NjIzOCwicGF0aCI6Ii8xMTQ3OTMzMzIvMzM1MTUxNzMyLTQxYzhkZDI0LWMzMzktNGQ4OS1hYzM3LWU5MzNhZjVlMjg5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxMDUwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE5MDU4M2IzYzhmNzg4YzYwZjlmNTUzY2M4MjYyMTI5MGU2ODU2OTdiZmNkYzEyZmNjYjhjNjllY2RjMGJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LLUUL2aM7a7iRqukhu0W22uus0rRvJpL347xw3JzP4k)

**Comment by Jackiechao020** [comment]
Hi Frank:

I found another error message. When I was calculating Ti-Nb example, using (111) twin as LIS, everything is correct and the code runs properly. Nevertheless, when I use (1 -1 1), the error message appears:
![螢幕擷取畫面 2024-05-30 224246](https://github.com/frankNiessen/PTMC/assets/114793332/ef89fa7f-ab1f-4e89-b3c7-e523d641ade2)
May I ask what is going wrong?Thank you!

**Comment by frankNiessen** [comment]
Hi Jackie, 

thank you for the hint. nntype is indeed part of the neural network toolbox, so this is quite suboptimal. 
I have now rewritten the normc function in a much simpler way and drafted a [new release](https://github.com/frankNiessen/PTMC/releases/tag/v1.0.1)

Best wishes
Frank
